version: '3.8'

services:
  frontend:
    image: nginx:latest
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - backend


  backend:
    image: python:3.9
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  proxy:
    image: nginx:latest
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend